version: '3.8'

services:
  mysql_wsi_db_1:
    container_name: "mysql_wsi_db_1"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - mysql_wsi_dev

  redis_wsi:
    container_name: "redis_wsi"
    image: redis:alpine
    restart: "no"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - mysql_wsi_dev


networks:
  mysql_wsi_dev:
