version: '3.8'

services:
  mysql_cfit_db_1:
    container_name: "mysql_cfit_db_1"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    env_file:
      - .env
    environment:
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - mysql_cfit_dev

  redis_cfit:
    container_name: "redis_cfit"
    image: redis:alpine
    restart: "no"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - mysql_cfit_dev

networks:
  mysql_cfit_dev:
